### ISSUE TITLE
Add commands to move windows between spaces

### ISSUE THREAD

**Issue by rossmacarthur** [scottwhudson/Lunette#5]
One of the biggest downsides of spectacle is that it doesn't support moving windows between spaces/desktops, it would great if Lunette could support this.

**Comment by scottwhudson** [comment]
This is a great suggestion. Unfortunately, hammerspoon doesn't have good API support for spaces, there's only a [basic watcher](http://www.hammerspoon.org/docs/hs.spaces.watcher.html) and the docs mention that the underlying OSX APIs have been deprecated.
