### ISSUE TITLE
Run commands directly

### ISSUE THREAD

**Issue by Thom1729** [scottwhudson/Lunette#7]
Thanks for writing Lunette; it's most of the reason I'm trying out Hammerspoon (replacing Spectacle for me).

I'm trying to use some of the Lunette commands directly from a script. I am new to Hammerspoon and to Lua, and I am most likely doing it wrong: `spoon.Lunette.exec("topHalf")`.

Is it possible to invoke Lunette commands directly? If, so, then a paragraph in the docs would be invaluable for novices like myself. If not, then that would be an extremely useful feature, at least for me.

**Comment by scottwhudson** [comment]
Great question, I haven't considered this use case before. I'll need to dig in before I can give a definitive answer as I'm fairly new to hammerspoon myself. But I see the value in this as a feature. Stay tuned!

**Comment by scottwhudson** [comment]
Hi @Thom1729, another contributor opened a PR to expose the resizer API that was just merged into v0.3. Feel free to give it a shot! I'm going to close this issue for now. If the new API changes don't meet your needs, just open another issue and we'll figure it out!
